android_stub: add missing definition
Fixes:

android_stub/sync_stub.cpp:18:11: error: use of undeclared identifier 'NULL'
   18 |    return NULL;
      |           ^~~~

Reviewed-by: Yonggang Luo <luoyonggang@gmail.com>
Reviewed-by: Yiwei Zhang <zzyiwei@chromium.org>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/38644>