nvk: silence error when cross-building for Android
When cross-building NVK for Android the compiler emits this error:

-----------------------------------------------------------------------
../src/nouveau/vulkan/nvk_image.c:1084:38: error: unused variable 'pdev' [-Werror,-Wunused-variable]
 1084 |    const struct nvk_physical_device *pdev = nvk_device_physical(dev);
      |                                      ^~~~
1 error generated.
-----------------------------------------------------------------------

Mark the variable definition as UNUSED to silence the error.

Acked-by: Valentine Burley <valentine.burley@collabora.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/36710>