FROMLIST: configure.ac: Fix -latomic test
When compiling with LLVM 6.0, the test fails to detect that
-latomic is actually required, as the atomic call is inlined.

In the code itself (src/util/disk_cache.c), we see this pattern:
p_atomic_add(cache->size, - (uint64_t)size);
where cache->size is an uint64_t *, and results in the following
link time error without -latomic:
src/util/disk_cache.c:628: error: undefined reference to '__atomic_fetch_add_8'

Fix the configure test to replicate this pattern, which then
correctly realizes the need for -latomic.

BUG=b:76397110
TEST=cros_workon_make --board=caroline-arcnext --reconf arc-mesa
(am from https://patchwork.freedesktop.org/patch/213657/, dropped
meson.build change)

Change-Id: I9cdad5fd32879a3577d6ef42e278960a934b23fb
Signed-off-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/985676
Reviewed-by: Tomasz Figa <tfiga@chromium.org>