ci/skqp: Add missing include to fix compilation errors on Debian 13
Include <cstdint> to fix these compilation errors:

../../src/sksl/SkSLString.h:124:18: error: unknown type name 'uint32_t'
  124 | String to_string(uint32_t value);
      |                  ^
../../src/sksl/SkSLString.h:128:18: error: unknown type name 'uint64_t'
  128 | String to_string(uint64_t value);
      |                  ^

Signed-off-by: Valentine Burley <valentine.burley@collabora.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/35853>