hk: Fix build error with static_assert
../src/asahi/vulkan/hk_cmd_draw.c: In function ‘hk_draw’:
../src/asahi/vulkan/hk_cmd_draw.c:3471:32: error: expression in static assertion is not constant
 3471 |             static_assert(size > sizeof(VkDrawIndirectCommand),
      |                           ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: 5bc89aa991eb ("hk,libagx: handle adjacency without a GS")
Closes: https://gitlab.freedesktop.org/mesa/mesa/-/issues/12351
Signed-off-by: Vinson Lee <vlee@freedesktop.org>
Reviewed-by: Eric Engestrom <None>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/32988>